version: '3'
services:
  openresty:
    image: 'openresty-test:0.1.0'
    container_name: openresty-test
    build:
      context: docker/openresty
    volumes:
      - ./docker/nginx/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./docker/nginx/conf/conf.d/:/etc/nginx/conf.d/
      - ./www/:/usr/local/openresty/nginx/html
      - ./code/:/code
      # - ./log/:/usr/local/openresty/nginx/logs/
    ports:
      - '4001:80'
    networks:
      - net-openresty
      - net-redis
    environment:
      - TZ=Asia/Shanghai
  redis:
    image: 'redis-test:0.1.0'
    container_name: redis-test
    build:
      context: docker/redis
    ports:
      - "6379:6379"
    networks:
      - net-redis
    environment:
      - TZ=Asia/Shanghai

networks:
  net-redis:
  net-openresty: